print("Hallo, gebruiker!")
naam = input("Wat is jouw naam? ")
print("Aha, hallo " + naam + "! Nu word ik nieuwsgierig.")
game = input("Wat is jouw favoriete game? ")
print("Dus jouw favourite game is " + game + "? Mooi.")
tijd = input("Hoe vaak heb jij het de laatste week gespeeld? ")
print("Dus jij hebt " + game + " deze week al " + tijd + " gespeeld.")